//
// Created by YongGyu Lee on 12/27/23.
//

#ifndef LSD_ALGORITHM_H_
#define LSD_ALGORITHM_H_

#include "lsd/__algorithm/clamp.h"
#include "lsd/__algorithm/for_each_n.h"
#include "lsd/__algorithm/shift.h"
#include "lsd/__algorithm/ranges/all_of.h"
#include "lsd/__algorithm/ranges/any_of.h"
#include "lsd/__algorithm/ranges/clamp.h"
#include "lsd/__algorithm/ranges/contains.h"
#include "lsd/__algorithm/ranges/contains_subrange.h"
#include "lsd/__algorithm/ranges/copy.h"
#include "lsd/__algorithm/ranges/count.h"
#include "lsd/__algorithm/ranges/count_if.h"
#include "lsd/__algorithm/ranges/equal.h"
#include "lsd/__algorithm/ranges/find.h"
#include "lsd/__algorithm/ranges/find_end.h"
#include "lsd/__algorithm/ranges/find_first_of.h"
#include "lsd/__algorithm/ranges/find_if.h"
#include "lsd/__algorithm/ranges/find_if_not.h"
#include "lsd/__algorithm/ranges/find_last.h"
#include "lsd/__algorithm/ranges/fold_left.h"
#include "lsd/__algorithm/ranges/for_each.h"
#include "lsd/__algorithm/ranges/for_each_n.h"
#include "lsd/__algorithm/ranges/in_found_result.h"
#include "lsd/__algorithm/ranges/in_fun_result.h"
#include "lsd/__algorithm/ranges/in_in_out_result.h"
#include "lsd/__algorithm/ranges/in_in_result.h"
#include "lsd/__algorithm/ranges/in_out_out_result.h"
#include "lsd/__algorithm/ranges/in_out_result.h"
#include "lsd/__algorithm/ranges/in_value_result.h"
#include "lsd/__algorithm/ranges/lexicographical_compare.h"
#include "lsd/__algorithm/ranges/make_heap.h"
#include "lsd/__algorithm/ranges/max.h"
#include "lsd/__algorithm/ranges/max_element.h"
#include "lsd/__algorithm/ranges/min.h"
#include "lsd/__algorithm/ranges/min_element.h"
#include "lsd/__algorithm/ranges/min_max_result.h"
#include "lsd/__algorithm/ranges/mismatch.h"
#include "lsd/__algorithm/ranges/none_of.h"
#include "lsd/__algorithm/ranges/out_value_result.h"
#include "lsd/__algorithm/ranges/pop_heap.h"
#include "lsd/__algorithm/ranges/search.h"
#include "lsd/__algorithm/ranges/set_intersection.h"
#include "lsd/__algorithm/ranges/sort.h"
#include "lsd/__algorithm/ranges/sort_heap.h"
#include "lsd/__algorithm/ranges/swap_ranges.h"

#endif // LSD_ALGORITHM_H_
